/*
 * TeamFlag.kt
 * Copyright (c) 2026. All rights reserved
 */
package com.myalbum2026.mobile.utils.ui

fun getFlagEmoji(teamId: String): String =
    when (teamId.uppercase()) {
        "SPECIALS" -> "⭐"
        "ALG" -> "🇩🇿"
        "ARG" -> "🇦🇷"
        "AUS" -> "🇦🇺"
        "AUT" -> "🇦🇹"
        "BEL" -> "🇧🇪"
        "BIH" -> "🇧🇦"
        "BRA" -> "🇧🇷"
        "CAN" -> "🇨🇦"
        "CPV" -> "🇨🇻"
        "COL" -> "🇨🇴"
        "CGO" -> "🇨🇬"
        "CRO" -> "🇭🇷"
        "CUW" -> "🇨🇼"
        "CZE" -> "🇨🇿"
        "ECU" -> "🇪🇨"
        "EGY" -> "🇪🇬"
        "ENG" -> "🏴󠁧󠁢󠁥󠁮󠁧󠁿"
        "FRA" -> "🇫🇷"
        "GER" -> "🇩🇪"
        "GHA" -> "🇬🇭"
        "HAI" -> "🇭🇹"
        "IRN" -> "🇮🇷"
        "IRQ" -> "🇮🇶"
        "CIV" -> "🇨🇮"
        "JPN" -> "🇯🇵"
        "JOR" -> "🇯🇴"
        "KOR" -> "🇰🇷"
        "MEX" -> "🇲🇽"
        "MAR" -> "🇲🇦"
        "NED" -> "🇳🇱"
        "NZL" -> "🇳🇿"
        "NOR" -> "🇳🇴"
        "PAN" -> "🇵🇦"
        "PAR" -> "🇵🇾"
        "POR" -> "🇵🇹"
        "QAT" -> "🇶🇦"
        "KSA" -> "🇸🇦"
        "SCO" -> "🏴󠁧󠁢󠁳󠁣󠁴󠁿"
        "SEN" -> "🇸🇳"
        "RSA" -> "🇿🇦"
        "ESP" -> "🇪🇸"
        "SWE" -> "🇸🇪"
        "SUI" -> "🇨🇭"
        "TUN" -> "🇹🇳"
        "TUR" -> "🇹🇷"
        "URU" -> "🇺🇾"
        "USA" -> "🇺🇸"
        "UZB" -> "🇺🇿"
        "TIMELINE" -> "⏳"
        "COCA-COLA" -> "🥤"
        else -> "🏳️"
    }
